# STAT 6205 Quiz 2 – Code Requirements (R Version)

Below code1–code18 need to be completed. Please fill in each section marked with `# your code here` accordingly.



## Data Loading
Load the digits dataset.

In [2]:

# -----------------------------
# 1. Data Loading
# -----------------------------
# Download and load the digits dataset from UCI.

digits_url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tes"
if (!file.exists("optdigits.tes")) {
  download.file(digits_url, destfile = "optdigits.tes")
}


In [3]:

# Read the data (comma-separated): first 64 columns are features, the 65th column is label.
digits_data <- read.table("optdigits.tes", sep = ",", header = FALSE)
X <- as.matrix(digits_data[, 1:64])
y <- digits_data[, 65]

cat("X shape:", dim(X), "\n")           # Should be (1797, 64)
cat("Unique labels:", sort(unique(y)), "\n")  # Expected: 0-9


X shape: 1797 64 
Unique labels: 0 1 2 3 4 5 6 7 8 9 


In [4]:


Xtrain <- X
ytrain <- y


### Q1 ML PPCA
Using X to calculate
- Mean:  $\mu = \bar{x}$
- Noise variance:  $\sigma^2_{ML} = \frac{1}{D-M} \sum_{m=M+1}^{D} \lambda_m$
- Loading matrix:  $W_{ML} = U_M \left(L_M - \sigma^2_{ML} I\right)^{1/2}$
- Posterior mean:  $E[z] = (W^T W+\sigma^2 I)^{-1} W^T (x-\mu)$
- Where:
  *  ${\bf U}_M$ is an $D \times M$ matrix whose columns are given by the $M$ eigenvectors with corresponding largest $M$ eigenvalues
  * ${\bf L}_M$ is a diagonal $M\times M$ matrix of the corresponding eigenvectors
  * ${\bf R}$ is an arbitrary orthogonal $M\times M$ matrix( we take ${\bf R}={\bf I}$)

In [5]:

M <- 2  # Latent dimension


### your code here  calculate the above 4 terms mu, sigma2_ml ,W_ml ,Ez_ml (code1-4)

In [6]:
# Hint for code1 (mu): Use colMeans() to compute sample mean
# Hint for code2 (sigma2_ml): Use eigen() to get eigenvalues, then sum and divide
# Hint for code3 (W_ml): Use eigenvectors, sqrt(), and matrix multiplication (%*%)
# Hint for code4 (Ez_ml): Use t(), %*%, solve() to compute the posterior mean

In [8]:
# code1
mu <- colMeans(Xtrain)
print(mu)


          V1           V2           V3           V4           V5           V6 
 0.000000000  0.303839733  5.204785754 11.835837507 11.848080134  5.781858653 
          V7           V8           V9          V10          V11          V12 
 1.362270451  0.129660545  0.005564830  1.993878687 10.382303840 11.979410128 
         V13          V14          V15          V16          V17          V18 
10.279354480  8.175848637  1.846410684  0.107957707  0.002782415  2.601558152 
         V19          V20          V21          V22          V23          V24 
 9.903171953  6.992765721  7.097941013  7.806343907  1.788536450  0.050083472 
         V25          V26          V27          V28          V29          V30 
 0.001112966  2.469671675  9.091263216  8.821368948  9.927100723  7.551474680 
         V31          V32          V33          V34          V35          V36 
 2.317751809  0.002225932  0.000000000  2.339454647  7.667223150  9.071786311 
         V37          V38          V39          V40 

In [57]:
#code2
X_cov <- cov(Xtrain)
eig <- eigen(X_cov)
eigenvalues <- eig$values
eigenvectors <- eig$vectors
D <- ncol(Xtrain)
m <- M+1
sigma2_ml <- sum(eigenvalues[m:D])/(D-M)
sigma2_ml


[1] 13.86166

In [192]:
#code3
U_M <- eigenvectors[,1:M]

W_ML <- U_M %*% diag(sqrt(eigenvalues[1:M]-sigma2_ml))
W_ML

0.000000000,0.0000000000
-0.222441961,0.1237189193
-2.871258459,0.6008765878
-1.746606365,0.1154793384
-0.424494437,0.6561674001
-1.241833592,1.4415102007
-0.107040658,0.7605465786
0.029158671,0.0971460034
-0.004118921,0.0019980236
-1.533225118,0.2572775240
-3.141420589,-0.7387613492


In [193]:
#code4
X_center <- scale(Xtrain, center  = TRUE, scale = FALSE)

E_z <- solve(t(W_ML) %*% W_ML + sigma2_ml * diag(M)) %*% t(W_ML) %*% t(X_center)
print(E_z)

            [,1]     [,2]      [,3]       [,4]      [,5]       [,6]      [,7]
[1,] -0.09041694 0.571276 0.5019493 -1.1418974  1.673197 -1.0113102  1.533677
[2,] -1.59077451 1.552926 0.7444332 -0.2491764 -0.319208 -0.5917825 -0.395422
           [,8]        [,9]      [,10]      [,11]     [,12]      [,13]
[1,] -0.2119673 -0.37726545 -0.3934228  0.8051292 0.2160288 -0.1733147
[2,]  1.5755793 -0.08848268 -0.6038863 -1.2651390 0.8968809  0.3627707
          [,14]      [,15]      [,16]     [,17]     [,18]      [,19]      [,20]
[1,] -1.6695180  1.7557460 -0.1005579 1.2323934 0.4031758 -0.2042533 -0.9886442
[2,]  0.1425727 -0.1989911  1.1859875 0.1786466 0.9665347  1.0684710 -0.6614672
         [,21]       [,22]      [,23]      [,24]      [,25]     [,26]
[1,]  0.461994 0.001856721 -0.5806967 -1.3776319  1.2591061 0.4387378
[2,] -1.456350 0.772925214  0.6588913  0.3376376 -0.3460264 0.4083997
          [,27]     [,28]      [,29]    [,30]       [,31]      [,32]      [,33]
[1,]  1.5315808 0.34285

## PPCA and the EM algorithm

An alternate way to estimate the parameters of the probabilistic PCA model is via the EM algorithm by considering the latent variable ${\bf z}_n$.

For PPCA, the expected value of the complete data log-likelihood with respect to the posterior latent distribution $Q = \mathbb{E}\left[\log p\left({\bf X}, {\bf Z}|\boldsymbol\mu, {\bf W}, \sigma^2\right)\right]$ is given by

$$
\begin{align}
    Q &=-\sum_{n=1}^N\Big\{\frac{M}{2}\log 2\pi + \text{Tr}\left(\mathbb{E}[{\bf z}_n{\bf z}_n^T]\right) + \frac{D}{2} \log2\pi\sigma^2\\
    %% Second term
    & + \frac{1}{2\sigma^2}\vert\vert{\bf x}_n - \bar{\bf x}\vert\vert - \frac{1}{\sigma^2}\mathbb{E}[{\bf z}_n]^T{\bf W}^T({\bf x}_n - \bar{\bf x}) + \frac{1}{\sigma^2}\text{Tr}\left(\mathbb{E}[{\bf z}_n{\bf z}_n^T]{\bf W}^T{\bf W}\right)\Big\}
\end{align}
$$


Recalling that $p({\bf z} \vert {\bf x}) = \mathcal{N}\left({\bf z}\vert {\bf M}^{-1}{\bf W}^T({\bf x}_n - \bar{\bf x}), \sigma^{-1}{\bf M}\right)$; ${\bf M} = {\bf W}^T{\bf W} + \sigma^2{\bf I}$ we obtain the following updating statistics:

$$
    \mathbb{E}[{\bf z}_n] = {\bf M}^{-1}{\bf W}^T({\bf x}_n - \bar{\bf x})
$$

$$
    \mathbb{E}\left[{\bf z}_n{\bf z}_n^T\right] = \mathbb{E}[{\bf z}_n]\mathbb{E}[{\bf z}_n]^T + \sigma^{-2}{\bf M}^{-1}
$$

Next, taking the derivative of $Q$ w.r.t. $\sigma^2$ and $\bf W$ and noting that $\mu_{\text{ML}} = \bar{\bf x}$, we obtain the updating equations:

$$
    \sigma_{\text{new}} = \frac{1}{ND}\sum_{n=1}^N \left\{\vert\vert{\bf x}_n - \bar{\bf x}\vert\vert^2 - 2\mathbb{E}[{\bf z}_n]^T{\bf W}^T({\bf x}_n - \bar{\bf x}) + \text{Tr}\left(\mathbb{E}[{\bf z}_n{\bf z}_n^T]{\bf W}^T{\bf W}\right)\right\}
$$

$$
    {\bf W}_{\text{new}} = \left(\sum_{n=1}^N\left({\bf x}_n - \bar{\bf x}_n\right)\mathbb{E}[{\bf z}_n]^T\right)\left(\sum_{n=1}^N\mathbb{E}\left[{\bf z}_n{\bf z}_n^T\right]\right)^{-1}
$$

Thus, we obtain the following updating equations
* **E**-step: Compute the sufficient statistics $\mathbb{E}\left[{\bf z}_n\right]$ and $\mathbb{E}\left[{\bf z}_n{\bf z}_n^T\right]$ considering the values ${\bf W}_\text{old}$ and $\sigma^2_\text{old}$
* **M**-step: Update ${\bf W}_\text{old}$, $\sigma^2_\text{old}$

## In the quiz, we just do one iteration to get the W_new and $\sigma_\text{new}^2$

In [60]:
# Get dimensions
N <- nrow(Xtrain)
D <- ncol(Xtrain)

In [61]:
# Initialize parameters
M <- 2  # Latent dimension
set.seed(42)  # For reproducibility
W <- matrix(rnorm(D * M), nrow = D, ncol = M)
sigma2 <- 0.5

In [62]:
# Center the data
Xhat <- scale(Xtrain, center = TRUE, scale = FALSE)


- **E-step:** For each sample $x_n$, compute:
  $$
  E[z_n] = (W^T W+\sigma^2 I)^{-1}W^T(x_n-\bar{x})
  $$
  $$
  E[z_n z_n^T] = E[z_n]E[z_n]^T + \sigma^2 (W^T W+\sigma^2 I)^{-1}
  $$

### your code here to calculate the above 2 terms and name them as E_zn, E_znzn (code5-6)

In [ ]:
# Hint for code5 (E_zn): Use solve(), %*%, t() to compute posterior means
# Hint for code6 (E_znzn): Create array(dim=c(M,M,N)), use outer products of expectation vectors


In [185]:
x_n <- Xhat[n,]
print(t(x_n))

     V1         V2       V3       V4       V5        V6       V7         V8
[1,]  0 -0.3038397 4.795214 2.164162 -3.84808 -4.781859 -1.36227 -0.1296605
              V9         V10      V11     V12       V13       V14       V15
[1,] -0.00556483 0.006121313 5.617696 2.02059 -4.279354 -7.175849 -1.846411
            V16          V17       V18      V19      V20      V21      V22
[1,] -0.1079577 -0.002782415 -2.601558 5.096828 8.007234 0.902059 7.193656
           V23         V24          V25       V26       V27      V28      V29
[1,] -1.788536 -0.05008347 -0.001112966 -2.469672 -4.091263 7.178631 6.072899
          V30       V31          V32 V33       V34      V35      V36      V37
[1,] 2.448525 -2.317752 -0.002225932   0 -2.339455 4.332777 5.928214 4.698386
          V38       V39 V40          V41      V42      V43       V44       V45
[1,] 3.255982 -2.909293   0 -0.008903728 2.416249 9.118531 -1.228158 -3.672231
          V46      V47         V48          V49      V50      V51       V52


In [184]:
# code5
x_n <- Xhat[n,]
for(n in 1:N){
  E_zn[,n] <- solve(t(W) %*% W + sigma2 * diag(M)) %*% t(W) %*% x_n
}



In [183]:
print(E_zn)

           [,1]       [,2]       [,3]       [,4]       [,5]       [,6]
[1,] 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246
[2,] 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758
           [,7]       [,8]       [,9]      [,10]      [,11]      [,12]
[1,] 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246
[2,] 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758
          [,13]      [,14]      [,15]      [,16]      [,17]      [,18]
[1,] 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246
[2,] 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758
          [,19]      [,20]      [,21]      [,22]      [,23]      [,24]
[1,] 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246
[2,] 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758 0.09035758
          [,25]      [,26]      [,27]      [,28]      [,29]      [,30]
[1,] 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246 0.14609246
[2,] 0

In [181]:
E_znzn <- array(0, dim=c(M,M,N))
print(E_znzn)

, , 1

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 2

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 3

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 4

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 5

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 6

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 7

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 8

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 9

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 10

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 11

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 12

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 13

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 14

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 15

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 16

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 17

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 18

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 19

     [,1] [,2]
[1,]    0    0

In [182]:
# code6
for(n in 1:N){
  E_znzn[,,n] <- outer(E_zn[,n] %*% t(E_zn[,n]) + sigma2 * solve(t(W) %*% W + sigma2 * diag(M)),n)
}


####   components in $\sigma_\text{new}^2$

$$
\sum_{n=1}^N \vert\vert{\bf x}_n - \bar{\bf x}\vert\vert^2
$$

### your code here: calculate the above term Xnorm2 using Xhat (code7)

In [69]:
# your code here: calculate the above term Xnorm2 using Xhat (code7)
# Hint: Use sum() and ^ operator to sum squared values
Xnorm2 <- sum(Xhat^2)

$$
-2\sum_{n=1}^N \left\{\mathbb{E}[{\bf z}_n]^T{\bf W}^T({\bf x}_n - \bar{\bf x})\right\}
$$

In [71]:
# Term: -2 * sum_{n=1}^N E[z_n]^T W^T (x_n - μ)
T2 <- 0
for (n in 1:N) {
  x_n <- Xhat[n, ]
  ez <- E_zn[, n]
  T2 <- T2 - 2 * sum((t(W) %*% x_n) * ez)
}

$$
\sum_{n=1}^N \left\{\text{Tr}\left(\mathbb{E}[{\bf z}_n{\bf z}_n^T]{\bf W}^T{\bf W}\right)\right\}
$$

In [180]:
# Term: sum_{n=1}^N Tr(E[z_n z_n^T] W^T W)
T3 <- 0
for (n in 1:N) {
  T3 <- T3 + sum(diag(W %*% E_znzn[,,n] %*% t(W)))
}


### your code here calculate sigma2_new using Xnorm2, T2, T3,N,D (code8)
$$
    \sigma_{\text{new}} = \frac{1}{ND}\sum_{n=1}^N \left\{\vert\vert{\bf x}_n - \bar{\bf x}\vert\vert^2 - 2\mathbb{E}[{\bf z}_n]^T{\bf W}^T({\bf x}_n - \bar{\bf x}) + \text{Tr}\left(\mathbb{E}[{\bf z}_n{\bf z}_n^T]{\bf W}^T{\bf W}\right)\right\}
$$

In [73]:
# your code here calculate sigma2_new using Xnorm2, T2, T3,N,D (code8)
# Hint: Use arithmetical operations like +, /, combine all terms according to the formula
sigma2_new <- (Xnorm2 + T2 + T3)/(N*D)


---

####  components in ${\bf W}_\text{new}$

$$
\sum_{n=1}^N\left({\bf x}_n - \bar{\bf x}_n\right)\mathbb{E}[{\bf z}_n]^T
$$

### your code here to calculate the above term using Xhat, E_z1 and name it as T1 (code9)


In [74]:
# Hint: Use matrix multiplication t(), %*% to multiply centered data with expected values


In [81]:
# T1 <-
  T1 <- t(Xhat) %*% t(E_zn)

$$
\sum_{n=1}^N\mathbb{E}\left[{\bf z}_n{\bf z}_n^T\right]
$$

### your code here to calculate the above term  using E_znzn and name it  as T2(code10)


In [82]:
# Hint: Use apply() to sum across samples in the 3D array E_znzn
# T2 <-
  T2 <- sum(E_znzn[,,1:N])

ERROR: Error in E_znzn[, , 1:N]: incorrect number of dimensions


### your code here to calculate the term W_new using T1, T2 (code11)
$$
    {\bf W}_{\text{new}} = \left(\sum_{n=1}^N\left({\bf x}_n - \bar{\bf x}_n\right)\mathbb{E}[{\bf z}_n]^T\right)\left(\sum_{n=1}^N\mathbb{E}\left[{\bf z}_n{\bf z}_n^T\right]\right)^{-1}
$$

In [ ]:
# your code here calculate the above term W_new using T1, T2 (code11)
# Hint: Use %*% and solve() to multiply T1 with the inverse of T2
# W_new <-

In [83]:
w_new <- T1 %*% solve(T2)

ERROR: Error in T1 %*% solve(T2): non-conformable arguments


## Image Denoising

In [90]:
library(ggplot2)
library(dplyr)
library(readr)
library(progress)
if (!require("gridExtra")) {
  install.packages("gridExtra")
}
# if not install mvtnorm, install it
if (!require("mvtnorm")) {
  install.packages("mvtnorm")
}
library(mvtnorm)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: gridExtra

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘gridExtra’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: mvtnorm

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘mvtnorm’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [91]:
# create the output directory
base_path <- "./outputR_logOdds"
if (!dir.exists(base_path)) {
  dir.create(base_path, recursive = TRUE)
}

In [92]:

# fix the random seed, ensuring reproducibility
set.seed(1)

# set the parameters
sigma <- 2

In [93]:
# read and preprocess the image
img <- read_csv("https://raw.githubusercontent.com/aqlkzf/STAT6205_quiz2_data/refs/heads/main/letterA.csv",
                col_names = FALSE)
img <- as.matrix(img)
mean_val <- mean(img)
img2 <- ifelse(img >= mean_val, 1, -1)
# add noise to the image
y <- img2 + sigma * matrix(rnorm(length(img2)), nrow = nrow(img2), ncol = ncol(img2))

Rows: 128 Columns: 128
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (128): X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [94]:
# load beta_s (logOdds) data
beta_s <- read_csv("https://github.com/aqlkzf/STAT6205_quiz2_data/raw/refs/heads/main/beta_s.csv")
logOdds <- as.matrix(beta_s)

Rows: 128 Columns: 128
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (128): 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


In [95]:
# plot the original binary image and the noisy image
pdf(file.path(base_path, "denoising.pdf"), width = 10, height = 5)
par(mfrow = c(1, 2))
image(t(img2[nrow(img2):1,]), col = grey.colors(100), axes = FALSE,
      main = "Original Binary Image")
image(t(y[nrow(y):1,]), col = grey.colors(100), axes = FALSE,
      main = "Noisy Image")
dev.off()


pdf 
  2

 ## Sigmoid Function

 The sigmoid function is defined as:

 $$\sigma(u) = \frac{1}{1+e^{-u}}$$

 This function maps any real-valued number to a value between 0 and 1, which can be interpreted as a probability.
 In the context of the Ising model, it's used to compute the probability of a pixel taking the value +1.


In [96]:
# define sigmoid function
sigmoid <- function(x) {
  1 / (1 + exp(-x))
}

## Neighbor Summation

This function calculates the total contribution of a pixel’s neighbors at position (ix, iy). It computes the neighbor sum using the formula:

$$\eta_s = \sum_{t \in \text{Nbr}(s)} \beta_{st} \cdot z_t$$

Where:
- $\text{Nbr}(s)$ represents the 4-connected neighbors (up, down, left, right) of pixel $s$
- $\beta_{st}$ is the interaction strength between pixels $s$ and $t$ (set to $J$ in this implementation)
- $z_t$ is the current state of neighbor pixel $t$

The function returns $2 \cdot J \cdot \sum_{t \in \text{Nbr}(s)} z_t$, which is used in both Gibbs sampling and mean field updates.


### your code here calculate the above neighbor sum (code12)


In [107]:
# your code here to calculate the above neighbor sum (code12)
NeighborSum <- function(ix, iy, X, J) {
  wi <- 0
  if(iy > 1){
    wi <- wi + X[iy-1, ix]
  }
  if(iy < ncol(X)){
    wi <- wi + X[iy+1, ix]
  }
  if(ix > 1){
    wi <- wi + X[iy, ix-1]
  }
  if(ix < nrow(X)){
    wi <- wi + X[iy, ix+1]
  }
  # your code here
  # Hint for code12: Check 4 neighbors (top/bottom/left/right) using if statements for boundary checks
  return(2 * J * wi)
}

## Gibbs Sampling Algorithm

Gibbs sampling is a Markov Chain Monte Carlo (MCMC) method used to sample from the posterior distribution in the Ising model.

### Algorithm:
1. **Initialization**:  
   Set each pixel $z_s$ by thresholding the noisy image:
   $$z_s^{(0)}=\begin{cases}
   +1 & \text{if } \text{img}_s \geq \text{mean(img)},\\
   -1 & \text{otherwise}.
   \end{cases}$$

2. **Iterative Updates**:
   - Randomly select a pixel $s \in V$
   - Compute the local field: $\eta_s = \sum_{t \in \text{Nbr}(s)} \beta_{st} \cdot z_t + \beta_s$
   - Compute the probability: $\theta_s = \sigma(2\eta_s)$, where $\sigma(u)=\frac{1}{1+e^{-u}}$
   - Sample the state of $s$ as:
     $$z_s=\begin{cases}
     +1 & \text{with probability }\theta_s,\\
     -1 & \text{with probability }1-\theta_s.
     \end{cases}$$

3. **Output**:
   - Return the final denoised binary image (each pixel is either +1 or -1).

In this implementation:
- $\beta_{st} = J = 1$ for all neighboring pixels
- $\beta_s$ is provided by the logOdds values (precomputed)



### your code here code13-15

In [111]:
# Gibbs sampling function
gibbs <- function(img, J, niter = 10, pre_computed_logOdds = NULL) {
  if (niter == 0) {
    return(img)
  }

  # initialize the binary image using the mean value of the original image
  mean_img <- mean(img)
  img2 <- ifelse(img >= mean_img, 1, -1)
  # use the pre-computed logOdds, otherwise calculate on the fly
  if (is.null(pre_computed_logOdds)) {
    # print error
    stop("Error: pre_computed_logOdds is NULL. Please provide precomputed logOdds values.")
 } else {
    logOdds_local <- pre_computed_logOdds
  }


  pb <- progress_bar$new(
    format = "Gibbs Sampling [:bar] :percent ETA: :eta",
    total = niter,
    clear = FALSE,
    width = 60
  )

  for (iter in 1:niter) {
    pb$tick()
    # your code here to randomly select a pixel (ix,iy)(code13)
    # Hint for code13: Use sample() to get random coordinates
    iy <- sample(1:ncol(img2), 1)
    ix <- sample(1:nrow(img2), 1)

    # your code here to calculate the neighbor sum   (code14)
    neighbor_sum <- NeighborSum(ix, iy, img2, J)
    # your code here to update the pixel value based neighbor sum and logOdds (code15)

    if(runif(1) < sigmoid(2*(neighbor_sum + logOdds_local[iy,ix]))){
      img2[iy,ix] <- 1
    }else{
      img2[iy,ix] <- -1
    }

}
  return(img2)
}


In [112]:
# set the random seed for sampling
set.seed(10)

# define the iteration counts (in terms of pixel updates)
iters <- c(82000, 163000)
cat("Iteration counts:", iters, "\n")

Iteration counts: 82000 163000 


In [113]:
# plot the Gibbs Sampling denoising results
pdf(file.path(base_path, "gibbsDenoising.pdf"), width = 4 * length(iters), height = 6)
par(mfrow = c(1, length(iters)), mar = c(2, 2,  6, 2))
for (i in seq_along(iters)) {
  result <- gibbs(y, J = 1, niter = iters[i], pre_computed_logOdds = logOdds)
  image(t(result[nrow(result):1,]), col = grey.colors(256), axes = FALSE,
        main = paste("iter =", iters[i]))
}
mtext("Gibbs Sampling (pixel-level updates)", side = 3, outer = TRUE, line = -1.5, cex = 1.6)
dev.off()

pdf 
  2

 ## Mean Field Variational Inference Algorithm

 Mean field variational inference approximates the posterior distribution by a factorized distribution where each pixel is independent.

 ### Algorithm:
 1. **Initialization**:  
    Set each pixel $\mu_s$ by thresholding the noisy image:
    $$\mu_s^{(0)}=\begin{cases}
    +1 & \text{if } \text{img}_s \geq \text{mean(img)},\\
    -1 & \text{otherwise}.
    \end{cases}$$

 2. **Iterative Updates**:
    - Randomly select a pixel $s \in V$
    - Update the mean for pixel $s$ via:
      $$\mu_s^{(k)} \leftarrow \tanh\left(\sum_{t \in \text{Nbr}(s)} \beta_{st} \cdot \mu_t^{(k-1)} + \beta_s\right)$$
    where the hyperbolic tangent is defined as $\tanh(x)=\frac{e^x-e^{-x}}{e^x+e^{-x}}$

 3. **Output**:
    - The final values of $\mu$ represent the expected values of the pixels in the denoised image.

 In this implementation:
 - $\beta_{st} = J = 1$ for all neighboring pixels
 - $\beta_s$ is provided by the logOdds values (precomputed)
 - A damping factor (rate) is applied to stabilize the updates

### your code here code16-18

In [117]:
# Mean Field update function
meanfield <- function(img, J, niter = 10, pre_computed_logOdds = NULL) {
  mean_img <- mean(img)
  img2 <- ifelse(img >= mean_img, 1, -1)
  if (is.null(pre_computed_logOdds)) {
    # print error
    stop("Error: pre_computed_logOdds is NULL. Please provide precomputed logOdds values.")
  } else {
    logOdds_local <- pre_computed_logOdds
  }

  # initialize the mean field state using the binary image
  mu <- matrix(img2, nrow = nrow(img2), ncol = ncol(img2))

  pb <- progress_bar$new(
    format = "Mean Field [:bar] :percent ETA: :eta",
    total = niter,
    clear = FALSE,
    width = 60
  )

  for (iter in 1:niter) {
    pb$tick()
    # your code here to randomly select a pixel (ix,iy)(code16)
    iy <- sample(1:ncol(img2), 1)
    ix <- sample(1:nrow(img2), 1)

    # your code here to calculate the neighbor sum   (code17)
    neighbor_sum <- NeighborSum(ix, iy, img2, J)
    # your code here to update the mean field estimate (code18)
    mu[iy,ix] <- tanh(neighbor_sum + logOdds_local[iy,ix])
  }

  return(mu)
}

In [115]:
# set the random seed for sampling
set.seed(10)

# define the iteration counts (in terms of pixel updates)
iters <- c(82000, 163000)
cat("Iteration counts:", iters, "\n")


Iteration counts: 82000 163000 


In [118]:
# plot the Mean Field denoising results
pdf(file.path(base_path, "meanFieldDenoising.pdf"), width = 4 * length(iters), height = 7)
par(mfrow = c(1, length(iters)), mar = c(2, 2, 6, 2))
for (i in seq_along(iters)) {
  result <- meanfield(y, J = 1, niter = iters[i], pre_computed_logOdds = logOdds)
  image(t(result[nrow(result):1,]), col = grey.colors(256), axes = FALSE,
        main = paste("iter =", iters[i]))
}
mtext("Mean Field (pixel-level updates)", side = 3, outer = TRUE, line = -1.5, cex = 1.6)
dev.off()

pdf 
  2